package com.example.book_store.dto;

public record BookDto(
        String bookId,  // Optional for requests, auto-generated by MongoDB
        String name,
        String price,
        String author,
        String description) {
}
